sudo /home/chix/qemu-2.9.0/x86_64-softmmu/qemu-system-x86_64 -vnc :11 \\n
		-enable-kvm -smp 8 -m 16384 \\n
		-drive file=/home/chix/kvm/image/image-11.img,if=virtio \\n
		-object memory-backend-file,id=mem,size=16384M,mem-path=/dev/hugepages,share=on \\n
		-numa node,memdev=mem -mem-prealloc \\n
		-chardev socket,id=char1,path=/home/chix/dpdk/socket/vhost-client-11-1,server \\n
		-netdev type=vhost-user,id=mynet1,chardev=char1,vhostforce \\n
		-device virtio-net-pci,mac=00:00:00:00:10:11,netdev=mynet1 \\n
		-chardev socket,id=char2,path=/home/chix/dpdk/socket/vhost-client-11-2,server \\n
		-netdev type=vhost-user,id=mynet2,chardev=char2,vhostforce \\n
		-device virtio-net-pci,mac=00:00:00:00:11:11,netdev=mynet2 \\n
