sudo /home/chix/qemu-2.9.0/x86_64-softmmu/qemu-system-x86_64 -vnc :38 \
		-enable-kvm -smp 8 -m 16384 \
		-drive file=/home/chix/kvm/image/image-38.img,if=virtio \
		-object memory-backend-file,id=mem,size=16384M,mem-path=/dev/hugepages,share=on \
		-numa node,memdev=mem -mem-prealloc \
		-chardev socket,id=char1,path=/home/chix/dpdk/socket/vhost-client-38-1,server \
		-netdev type=vhost-user,id=mynet1,chardev=char1,vhostforce \
		-device virtio-net-pci,mac=00:00:00:00:10:38,netdev=mynet1 \
		-chardev socket,id=char2,path=/home/chix/dpdk/socket/vhost-client-38-2,server \
		-netdev type=vhost-user,id=mynet2,chardev=char2,vhostforce \
		-device virtio-net-pci,mac=00:00:00:00:11:38,netdev=mynet2
